# Generated by Django 4.2.11 on 2026-04-18 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('component_type', models.CharField(choices=[('WB', 'Whole Blood'), ('RBC', 'Red Blood Cells'), ('PLT', 'Platelets'), ('PLS', 'Fresh Frozen Plasma')], default='WB', max_length=3)),
                ('units_required', models.PositiveIntegerField()),
                ('units_fulfilled', models.PositiveIntegerField(default=0)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent (within 24 hours)'), ('CRITICAL', 'Critical (immediate)')], default='ROUTINE', max_length=10)),
                ('required_by_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_units', models.ManyToManyField(blank=True, related_name='fulfils_request', to='inventory.bloodunit')),
                ('requested_by', models.ForeignKey(help_text='Hospital user who raised this request.', on_delete=django.db.models.deletion.PROTECT, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Request',
                'verbose_name_plural': 'Blood Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'urgency'], name='blood_reque_status_99c702_idx'), models.Index(fields=['blood_group', 'status'], name='blood_reque_blood_g_401836_idx'), models.Index(fields=['required_by_date'], name='blood_reque_require_cd42bf_idx')],
            },
        ),
    ]
