# Generated by Django 4.2.11 on 2026-04-18 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('component_type', models.CharField(choices=[('WB', 'Whole Blood'), ('RBC', 'Red Blood Cells'), ('PLT', 'Platelets'), ('PLS', 'Fresh Frozen Plasma')], default='WB', max_length=3)),
                ('volume_ml', models.PositiveIntegerField(default=450, help_text='Volume in millilitres')),
                ('collected_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], default='AVAILABLE', max_length=10)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donated_units', to='donors.donorprofile')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Unit',
                'verbose_name_plural': 'Blood Units',
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['blood_group', 'status'], name='inventory_b_blood_g_ab68f5_idx'), models.Index(fields=['expiry_date'], name='inventory_b_expiry__6699fc_idx')],
            },
        ),
    ]
