# Generated by Django 4.2.11 on 2026-04-18 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donors', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected (medically unfit)')], default='SCHEDULED', max_length=10)),
                ('component_type', models.CharField(choices=[('WB', 'Whole Blood'), ('RBC', 'Red Blood Cells'), ('PLT', 'Platelets'), ('PLS', 'Fresh Frozen Plasma')], default='WB', max_length=3)),
                ('volume_ml', models.PositiveIntegerField(default=450)),
                ('blood_group', models.CharField(blank=True, max_length=3)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation', to='inventory.bloodunit')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donors.donorprofile')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['donor', 'status'], name='donations_d_donor_i_d5122b_idx'), models.Index(fields=['scheduled_date'], name='donations_d_schedul_986c46_idx')],
            },
        ),
    ]
